I fixed an `AttributeError: module 'os' has no attribute 'setsid'` on Windows by using the `subprocess.CREATE_NEW_PROCESS_GROUP` flag instead of `os.setsid` when running on Windows.